version: 2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '12.6'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build:contracts
          name: Compile contracts
      - run:
          command: yarn chain
          name: Start blockchain
          background: true
      - run:
          # Wait for the blockchain to start at port 8545. We expect a 400 response so we 
          # override the shell and have the last command be the : { null } command to force exit code 0.
          shell: /bin/sh
          command: |
                wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8545
                :
          name: Wait for blockchain to start
      - run:
          command: yarn run test
          name: Run tests
orbs:
  node: circleci/node@4.1.0
workflows:
  test_contracts:
    jobs:
      - test
